apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: applications.alustan.io
spec:
  group: alustan.io
  names:
    kind: Application
    listKind: ApplicationList
    plural: applications
    singular: application
    shortNames:
      - app
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
              properties:
                name:
                  type: string
            spec:
              type: object
              required:
                - cluster
                - environment
                - port
                - provider
              properties:
                provider:
                  type: string
                cluster:
                  type: string
                environment:
                  type: string
                
                port:
                  type: integer
                host:
                  type: string
                strategy:
                  type: string
                git:
                  type: object
                  properties:
                    owner:
                      type: string
                    repo:
                      type: string
                   
                    branch:
                      type: string
                containerRegistry:
                  type: object
                  properties:
                    provider:
                      type: string
                    imageName:
                      type: string
                    semanticVersion:
                      type: string
                      
                config:
                  type: object
                  additionalProperties: true
                
            status:
              type: object
              properties:
                message:
                  type: string
                healthStatus:
                  type: string
               
      subresources:
        status: {}
                