apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: terraforms.alustan.io
spec:
  group: alustan.io
  names:
    plural: terraforms
    singular: terraform
    kind: Terraform
    shortNames:
      - tf
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                variables:
                  type: object
                  additionalProperties: true
                scripts:
                  type: object
                  properties:
                    deploy:
                      type: string
                    destroy:
                      type: string
                postDeploy:
                  type: object
                  properties:
                    script:
                      type: string
                    args:
                      type: object
                      additionalProperties: true
                containerRegistry:
                  type: object
                  properties:
                    provider:
                      type: string
                    imageName:
                      type: string
                    semanticVersion:
                      type: string
            status:
              type: object
              properties:
                state:
                  type: string
                message:
                  type: string
                finalized:
                  type: boolean
                output:
                  type: object
                  additionalProperties: true
                postDeployOutput:
                  type: object
                  additionalProperties: true
                ingressURLs:
                  type: object
                  additionalProperties: true
                credentials:
                  type: object
                  additionalProperties: true
      subresources:
        status: {}
