apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-controller-helm
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "app-controller-helm.labels" . | nindent 4 }}
spec:
 
  replicas: {{ .Values.app.replicaCount }}
 
  selector:
    matchLabels:
      {{- include "app-controller-helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
     
      labels:
        {{- include "app-controller-helm.labels" . | nindent 8 }}
       
    spec:
     
      
      serviceAccountName: app-sa
     
      
      containers:
        - name: {{ .Chart.Name }}
          
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
          env:
            - name: APP_SYNC_INTERVAL
              value: {{ .Values.app.syncInterval }}

            - name: ARGOCD_CONFIG
              value: {{ .Values.argocdConfig }}

              
           
          {{- if .Values.useSecrets }}
            - name: CONTAINER_REGISTRY_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.containerRegistrySecretName }}
                  key: {{ .Values.containerRegistrySecretKey }}

            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.githubTokenSecretName }}
                  key: {{ .Values.githubTokenSecretKey }}
           
            {{- else }}
           
           
            - name: CONTAINER_REGISTRY_SECRET
              value: {{ .Values.containerRegistry.containerRegistrySecret }}
             
            - name: GITHUB_TOKEN
              value: {{ .Values.githubToken}}
         
           
            {{- end }}
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.app.service.port }}
              protocol: TCP
          
         
