

replicaCount: 1
namespace: alustan
image:
  pullPolicy: IfNotPresent
  infra:
    repository: alustan/terraform-controller
    
    # Overrides the image tag whose default is the chart appVersion.
    tag: "v0.16.0"
  app:
    repository: alustan/app-controller
  
    # Overrides the image tag whose default is the chart appVersion.
    tag: "v0.1.0"


imagePullSecrets: []


infraSyncInterval: ""

appSyncInterval: ""

gitOrg:
  url: https://github.com/alustan
  gitSSHSecret: "" # specify if using private git repo
  githubToken: ""  # specify if using ghcr as container registry

containerRegistry:
  containerRegistrySecret: "" # required by terraform-controller to push and pull image from regstry
  dockerToken: "" # specify if using docker as container registry



# wish to Use Kubernetes Secrets
useSecrets: false
containerRegistrySecretName: ""
containerRegistrySecretKey: ""
dockerToken: ""
gitSecretName: ""
gitSSHSecretKey: ""
githubToken: ""


serviceAccount:
   # Specifies whether a service account should be created
  create: false
 # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: 
    # eks.amazonaws.com/role-arn: ""
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "default" # change to name of service account with necessary arn annotations

podAnnotations: {}
podLabels: {}


service:
  type: ClusterIP
  infra:
    port:  8080 
  app:
    port:  8081



autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

